In [1]:
import gym
import numpy as np

### Load the environment

In [2]:
env = gym.make('FrozenLake-v0')

### Implement Q-Table Learning Algorithm

In [24]:
Q = np.zeros([env.observation_space.n, env.action_space.n])
lr = .8
y = .95
num_episodes = 2000
rList = []

for i in range(num_episodes):
    s = env.reset()
    rAll = 0
    done = False
    j = 0
    while j < 99:
        j+=1
        a = np.argmax(Q[s,:] + np.random.rand(1, env.action_space.n)*(1./(i+1)))
        s1, reward, done, _ = env.step(a)
        Q[s,a] = Q[s,a] + lr*(reward + y*np.max(Q[s1,:]) - Q[s,a])
        rAll += reward
        s = s1
        
        if done == True:
            break
    rList.append(rAll)

In [25]:
print( "Score over time: " + str(sum(rList)/num_episodes))

Score over time: 0.5545


In [26]:
print("Final Q-Table Values: ")
print(Q)

Final Q-Table Values: 
[[2.14326626e-01 2.21132131e-03 3.44587374e-03 1.97371690e-03]
 [4.52959412e-04 7.45204976e-05 2.04334300e-03 1.78207715e-01]
 [2.05601538e-03 1.42770957e-01 1.95535432e-03 2.04464147e-03]
 [2.24620770e-03 2.88777734e-04 0.00000000e+00 9.94458561e-02]
 [2.44932555e-01 2.38668538e-03 5.37318437e-04 6.13393337e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [9.68960578e-03 3.47009044e-07 1.20530253e-04 1.74184205e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [8.31910682e-04 1.48348872e-04 2.94643245e-03 1.92426077e-01]
 [0.00000000e+00 2.88382082e-01 2.43347608e-03 0.00000000e+00]
 [1.46682644e-01 4.95188786e-04 1.05690874e-04 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [7.65303721e-04 1.31195752e-04 7.83121804e-01 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 5.31532038e-01 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 